'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace HsVerwSvc
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Verbrauch", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Verbrauch
        Inherits HsVerwSvc.IService1Basis
        
        Private VerbrauchstypField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Verbrauchstyp() As String
            Get
                Return Me.VerbrauchstypField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerbrauchstypField, value) <> true) Then
                    Me.VerbrauchstypField = value
                    Me.RaisePropertyChanged("Verbrauchstyp")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IService1.Basis", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(HsVerwSvc.Ausgabe)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(HsVerwSvc.Einnahme)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(HsVerwSvc.Verbrauch))>  _
    Partial Public Class IService1Basis
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private DatumField As Date
        
        Private EinheitField As String
        
        Private EinheitIDField As Long
        
        Private HaushaltskategorieField As String
        
        Private HaushaltskategorieIDField As Long
        
        Private HaushaltsunterkategorieField As String
        
        Private HaushaltsunterkategorieIDField As Long
        
        Private IDField As Long
        
        Private WertField As Long
        
        Private ZahlungsrythmusField As String
        
        Private ZahlungsrythmusIDField As Long
        
        Private ZahlungsrythmusfaktorField As Long
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Datum() As Date
            Get
                Return Me.DatumField
            End Get
            Set
                If (Me.DatumField.Equals(value) <> true) Then
                    Me.DatumField = value
                    Me.RaisePropertyChanged("Datum")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Einheit() As String
            Get
                Return Me.EinheitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EinheitField, value) <> true) Then
                    Me.EinheitField = value
                    Me.RaisePropertyChanged("Einheit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EinheitID() As Long
            Get
                Return Me.EinheitIDField
            End Get
            Set
                If (Me.EinheitIDField.Equals(value) <> true) Then
                    Me.EinheitIDField = value
                    Me.RaisePropertyChanged("EinheitID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Haushaltskategorie() As String
            Get
                Return Me.HaushaltskategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltskategorieField, value) <> true) Then
                    Me.HaushaltskategorieField = value
                    Me.RaisePropertyChanged("Haushaltskategorie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HaushaltskategorieID() As Long
            Get
                Return Me.HaushaltskategorieIDField
            End Get
            Set
                If (Me.HaushaltskategorieIDField.Equals(value) <> true) Then
                    Me.HaushaltskategorieIDField = value
                    Me.RaisePropertyChanged("HaushaltskategorieID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Haushaltsunterkategorie() As String
            Get
                Return Me.HaushaltsunterkategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltsunterkategorieField, value) <> true) Then
                    Me.HaushaltsunterkategorieField = value
                    Me.RaisePropertyChanged("Haushaltsunterkategorie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HaushaltsunterkategorieID() As Long
            Get
                Return Me.HaushaltsunterkategorieIDField
            End Get
            Set
                If (Me.HaushaltsunterkategorieIDField.Equals(value) <> true) Then
                    Me.HaushaltsunterkategorieIDField = value
                    Me.RaisePropertyChanged("HaushaltsunterkategorieID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Wert() As Long
            Get
                Return Me.WertField
            End Get
            Set
                If (Me.WertField.Equals(value) <> true) Then
                    Me.WertField = value
                    Me.RaisePropertyChanged("Wert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zahlungsrythmus() As String
            Get
                Return Me.ZahlungsrythmusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZahlungsrythmusField, value) <> true) Then
                    Me.ZahlungsrythmusField = value
                    Me.RaisePropertyChanged("Zahlungsrythmus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZahlungsrythmusID() As Long
            Get
                Return Me.ZahlungsrythmusIDField
            End Get
            Set
                If (Me.ZahlungsrythmusIDField.Equals(value) <> true) Then
                    Me.ZahlungsrythmusIDField = value
                    Me.RaisePropertyChanged("ZahlungsrythmusID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zahlungsrythmusfaktor() As Long
            Get
                Return Me.ZahlungsrythmusfaktorField
            End Get
            Set
                If (Me.ZahlungsrythmusfaktorField.Equals(value) <> true) Then
                    Me.ZahlungsrythmusfaktorField = value
                    Me.RaisePropertyChanged("Zahlungsrythmusfaktor")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ausgabe", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Ausgabe
        Inherits HsVerwSvc.IService1Basis
        
        Private AusgabentypField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ausgabentyp() As String
            Get
                Return Me.AusgabentypField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusgabentypField, value) <> true) Then
                    Me.AusgabentypField = value
                    Me.RaisePropertyChanged("Ausgabentyp")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Einnahme", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Einnahme
        Inherits HsVerwSvc.IService1Basis
        
        Private EinnahmentypField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Einnahmentyp() As String
            Get
                Return Me.EinnahmentypField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EinnahmentypField, value) <> true) Then
                    Me.EinnahmentypField = value
                    Me.RaisePropertyChanged("Einnahmentyp")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IService1.Verbrauchstyp", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class IService1Verbrauchstyp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private HaushaltskategorieField As String
        
        Private HaushaltskategorieIDField As Long
        
        Private HaushaltsunterkategorieField As String
        
        Private IDField As Long
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Haushaltskategorie() As String
            Get
                Return Me.HaushaltskategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltskategorieField, value) <> true) Then
                    Me.HaushaltskategorieField = value
                    Me.RaisePropertyChanged("Haushaltskategorie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HaushaltskategorieID() As Long
            Get
                Return Me.HaushaltskategorieIDField
            End Get
            Set
                If (Me.HaushaltskategorieIDField.Equals(value) <> true) Then
                    Me.HaushaltskategorieIDField = value
                    Me.RaisePropertyChanged("HaushaltskategorieID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Haushaltsunterkategorie() As String
            Get
                Return Me.HaushaltsunterkategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltsunterkategorieField, value) <> true) Then
                    Me.HaushaltsunterkategorieField = value
                    Me.RaisePropertyChanged("Haushaltsunterkategorie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Zahlungsrythmus", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Zahlungsrythmus
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private BeginnField As Date
        
        Private IDField As Long
        
        Private RythmusField As String
        
        Private RythmusfaktorField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Beginn() As Date
            Get
                Return Me.BeginnField
            End Get
            Set
                If (Me.BeginnField.Equals(value) <> true) Then
                    Me.BeginnField = value
                    Me.RaisePropertyChanged("Beginn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rythmus() As String
            Get
                Return Me.RythmusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RythmusField, value) <> true) Then
                    Me.RythmusField = value
                    Me.RaisePropertyChanged("Rythmus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rythmusfaktor() As Integer
            Get
                Return Me.RythmusfaktorField
            End Get
            Set
                If (Me.RythmusfaktorField.Equals(value) <> true) Then
                    Me.RythmusfaktorField = value
                    Me.RaisePropertyChanged("Rythmusfaktor")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Einheit", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Einheit
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private EinheitMemberField As String
        
        Private IDField As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="Einheit")>  _
        Public Property EinheitMember() As String
            Get
                Return Me.EinheitMemberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EinheitMemberField, value) <> true) Then
                    Me.EinheitMemberField = value
                    Me.RaisePropertyChanged("EinheitMember")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VarVerbrauchKat", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class VarVerbrauchKat
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private IDField As Long
        
        Private VarVerbrauchKatMemberField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="VarVerbrauchKat")>  _
        Public Property VarVerbrauchKatMember() As String
            Get
                Return Me.VarVerbrauchKatMemberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VarVerbrauchKatMemberField, value) <> true) Then
                    Me.VarVerbrauchKatMemberField = value
                    Me.RaisePropertyChanged("VarVerbrauchKatMember")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Haushaltskategorie", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Haushaltskategorie
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private HaushaltskategorieMemberField As String
        
        Private IDField As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="Haushaltskategorie")>  _
        Public Property HaushaltskategorieMember() As String
            Get
                Return Me.HaushaltskategorieMemberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltskategorieMemberField, value) <> true) Then
                    Me.HaushaltskategorieMemberField = value
                    Me.RaisePropertyChanged("HaushaltskategorieMember")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Haushaltsunterkategorie", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Haushaltsunterkategorie
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private HaushaltsunterkategorieMemberField As String
        
        Private IDField As Long
        
        Private KategorieIDField As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="Haushaltsunterkategorie")>  _
        Public Property HaushaltsunterkategorieMember() As String
            Get
                Return Me.HaushaltsunterkategorieMemberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HaushaltsunterkategorieMemberField, value) <> true) Then
                    Me.HaushaltsunterkategorieMemberField = value
                    Me.RaisePropertyChanged("HaushaltsunterkategorieMember")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property KategorieID() As Long
            Get
                Return Me.KategorieIDField
            End Get
            Set
                If (Me.KategorieIDField.Equals(value) <> true) Then
                    Me.KategorieIDField = value
                    Me.RaisePropertyChanged("KategorieID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Auswertung", [Namespace]:="http://schemas.datacontract.org/2004/07/HsVerwWCFService")>  _
    Partial Public Class Auswertung
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AusgabenFixproJahrField As String
        
        Private AusgabenFixproMonatField As String
        
        Private AusgabenVarproJahrField As String
        
        Private AusgabenVarproMonatField As String
        
        Private AuswertungproJahrField As String
        
        Private AuswertungproMonatField As String
        
        Private EinnahmenproJahrField As String
        
        Private EinnahmenproMonatField As String
        
        Private VerbrauchFixproJahrField As String
        
        Private VerbrauchFixproMonatField As String
        
        Private VerbrauchVarproJahrField As String
        
        Private VerbrauchVarproMonatField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AusgabenFixproJahr() As String
            Get
                Return Me.AusgabenFixproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusgabenFixproJahrField, value) <> true) Then
                    Me.AusgabenFixproJahrField = value
                    Me.RaisePropertyChanged("AusgabenFixproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AusgabenFixproMonat() As String
            Get
                Return Me.AusgabenFixproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusgabenFixproMonatField, value) <> true) Then
                    Me.AusgabenFixproMonatField = value
                    Me.RaisePropertyChanged("AusgabenFixproMonat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AusgabenVarproJahr() As String
            Get
                Return Me.AusgabenVarproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusgabenVarproJahrField, value) <> true) Then
                    Me.AusgabenVarproJahrField = value
                    Me.RaisePropertyChanged("AusgabenVarproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AusgabenVarproMonat() As String
            Get
                Return Me.AusgabenVarproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusgabenVarproMonatField, value) <> true) Then
                    Me.AusgabenVarproMonatField = value
                    Me.RaisePropertyChanged("AusgabenVarproMonat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuswertungproJahr() As String
            Get
                Return Me.AuswertungproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuswertungproJahrField, value) <> true) Then
                    Me.AuswertungproJahrField = value
                    Me.RaisePropertyChanged("AuswertungproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuswertungproMonat() As String
            Get
                Return Me.AuswertungproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuswertungproMonatField, value) <> true) Then
                    Me.AuswertungproMonatField = value
                    Me.RaisePropertyChanged("AuswertungproMonat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EinnahmenproJahr() As String
            Get
                Return Me.EinnahmenproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EinnahmenproJahrField, value) <> true) Then
                    Me.EinnahmenproJahrField = value
                    Me.RaisePropertyChanged("EinnahmenproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EinnahmenproMonat() As String
            Get
                Return Me.EinnahmenproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EinnahmenproMonatField, value) <> true) Then
                    Me.EinnahmenproMonatField = value
                    Me.RaisePropertyChanged("EinnahmenproMonat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VerbrauchFixproJahr() As String
            Get
                Return Me.VerbrauchFixproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerbrauchFixproJahrField, value) <> true) Then
                    Me.VerbrauchFixproJahrField = value
                    Me.RaisePropertyChanged("VerbrauchFixproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VerbrauchFixproMonat() As String
            Get
                Return Me.VerbrauchFixproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerbrauchFixproMonatField, value) <> true) Then
                    Me.VerbrauchFixproMonatField = value
                    Me.RaisePropertyChanged("VerbrauchFixproMonat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VerbrauchVarproJahr() As String
            Get
                Return Me.VerbrauchVarproJahrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerbrauchVarproJahrField, value) <> true) Then
                    Me.VerbrauchVarproJahrField = value
                    Me.RaisePropertyChanged("VerbrauchVarproJahr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VerbrauchVarproMonat() As String
            Get
                Return Me.VerbrauchVarproMonatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerbrauchVarproMonatField, value) <> true) Then
                    Me.VerbrauchVarproMonatField = value
                    Me.RaisePropertyChanged("VerbrauchVarproMonat")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HsVerwSvc.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauch", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchResponse")>  _
        Function GetVerbrauchAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAusgaben", ReplyAction:="http://tempuri.org/IService1/GetAusgabenResponse")>  _
        Function GetAusgabenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Ausgabe))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetEinnahmen", ReplyAction:="http://tempuri.org/IService1/GetEinnahmenResponse")>  _
        Function GetEinnahmenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Einnahme))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauchbyTyp", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchbyTypResponse")>  _
        Function GetVerbrauchbyTypAsync(ByVal verbrauchstyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauchsTyp", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchsTypResponse")>  _
        Function GetVerbrauchsTypAsync(ByVal Haushatskategorie_ID As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.IService1Verbrauchstyp))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauchbyUnterTyp", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchbyUnterTypResponse")>  _
        Function GetVerbrauchbyUnterTypAsync(ByVal verbrauchsuntertyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAusgabebyTyp", ReplyAction:="http://tempuri.org/IService1/GetAusgabebyTypResponse")>  _
        Function GetAusgabebyTypAsync(ByVal ausgabentyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Ausgabe))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauchbyID", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchbyIDResponse")>  _
        Function GetVerbrauchbyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Verbrauch)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAusgabebyID", ReplyAction:="http://tempuri.org/IService1/GetAusgabebyIDResponse")>  _
        Function GetAusgabebyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Ausgabe)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVerbrauchbyDate", ReplyAction:="http://tempuri.org/IService1/GetVerbrauchbyDateResponse")>  _
        Function GetVerbrauchbyDateAsync(ByVal datum As Date) As System.Threading.Tasks.Task(Of HsVerwSvc.Verbrauch)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAusgabebyDate", ReplyAction:="http://tempuri.org/IService1/GetAusgabebyDateResponse")>  _
        Function GetAusgabebyDateAsync(ByVal datum As Date) As System.Threading.Tasks.Task(Of HsVerwSvc.Ausgabe)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetZahlungsrythmen", ReplyAction:="http://tempuri.org/IService1/GetZahlungsrythmenResponse")>  _
        Function GetZahlungsrythmenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Zahlungsrythmus))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetEinheiten", ReplyAction:="http://tempuri.org/IService1/GetEinheitenResponse")>  _
        Function GetEinheitenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Einheit))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetVarVerbrauchKat", ReplyAction:="http://tempuri.org/IService1/GetVarVerbrauchKatResponse")>  _
        Function GetVarVerbrauchKatAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.VarVerbrauchKat))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetVerbrauch", ReplyAction:="http://tempuri.org/IService1/SetVerbrauchResponse")>  _
        Function SetVerbrauchAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetAusgabe", ReplyAction:="http://tempuri.org/IService1/SetAusgabeResponse")>  _
        Function SetAusgabeAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetEinnahme", ReplyAction:="http://tempuri.org/IService1/SetEinnahmeResponse")>  _
        Function SetEinnahmeAsync(ByVal vlo_einnahme As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetVerbrauchNew", ReplyAction:="http://tempuri.org/IService1/SetVerbrauchNewResponse")>  _
        Function SetVerbrauchNewAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetAusgabeNew", ReplyAction:="http://tempuri.org/IService1/SetAusgabeNewResponse")>  _
        Function SetAusgabeNewAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SetEinnahmeNew", ReplyAction:="http://tempuri.org/IService1/SetEinnahmeNewResponse")>  _
        Function SetEinnahmeNewAsync(ByVal vlo_ausgabe As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteVerbrauch", ReplyAction:="http://tempuri.org/IService1/DeleteVerbrauchResponse")>  _
        Function DeleteVerbrauchAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteAusgabe", ReplyAction:="http://tempuri.org/IService1/DeleteAusgabeResponse")>  _
        Function DeleteAusgabeAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteEinnahme", ReplyAction:="http://tempuri.org/IService1/DeleteEinnahmeResponse")>  _
        Function DeleteEinnahmeAsync(ByVal vlo_ausgabe As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetHaushaltskategorien", ReplyAction:="http://tempuri.org/IService1/GetHaushaltskategorienResponse")>  _
        Function GetHaushaltskategorienAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Haushaltskategorie))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetHaushaltsunterkategorien", ReplyAction:="http://tempuri.org/IService1/GetHaushaltsunterkategorienResponse")>  _
        Function GetHaushaltsunterkategorienAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Haushaltsunterkategorie))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAuswertung", ReplyAction:="http://tempuri.org/IService1/GetAuswertungResponse")>  _
        Function GetAuswertungAsync() As System.Threading.Tasks.Task(Of HsVerwSvc.Auswertung)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetEinnahmebyID", ReplyAction:="http://tempuri.org/IService1/GetEinnahmebyIDResponse")>  _
        Function GetEinnahmebyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Einnahme)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits HsVerwSvc.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of HsVerwSvc.IService1)
        Implements HsVerwSvc.IService1
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(Service1Client.GetDefaultBinding, Service1Client.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetVerbrauchAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch)) Implements HsVerwSvc.IService1.GetVerbrauchAsync
            Return MyBase.Channel.GetVerbrauchAsync
        End Function
        
        Public Function GetAusgabenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Ausgabe)) Implements HsVerwSvc.IService1.GetAusgabenAsync
            Return MyBase.Channel.GetAusgabenAsync
        End Function
        
        Public Function GetEinnahmenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Einnahme)) Implements HsVerwSvc.IService1.GetEinnahmenAsync
            Return MyBase.Channel.GetEinnahmenAsync
        End Function
        
        Public Function GetVerbrauchbyTypAsync(ByVal verbrauchstyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch)) Implements HsVerwSvc.IService1.GetVerbrauchbyTypAsync
            Return MyBase.Channel.GetVerbrauchbyTypAsync(verbrauchstyp)
        End Function
        
        Public Function GetVerbrauchsTypAsync(ByVal Haushatskategorie_ID As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.IService1Verbrauchstyp)) Implements HsVerwSvc.IService1.GetVerbrauchsTypAsync
            Return MyBase.Channel.GetVerbrauchsTypAsync(Haushatskategorie_ID)
        End Function
        
        Public Function GetVerbrauchbyUnterTypAsync(ByVal verbrauchsuntertyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Verbrauch)) Implements HsVerwSvc.IService1.GetVerbrauchbyUnterTypAsync
            Return MyBase.Channel.GetVerbrauchbyUnterTypAsync(verbrauchsuntertyp)
        End Function
        
        Public Function GetAusgabebyTypAsync(ByVal ausgabentyp As Long) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Ausgabe)) Implements HsVerwSvc.IService1.GetAusgabebyTypAsync
            Return MyBase.Channel.GetAusgabebyTypAsync(ausgabentyp)
        End Function
        
        Public Function GetVerbrauchbyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Verbrauch) Implements HsVerwSvc.IService1.GetVerbrauchbyIDAsync
            Return MyBase.Channel.GetVerbrauchbyIDAsync(ID)
        End Function
        
        Public Function GetAusgabebyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Ausgabe) Implements HsVerwSvc.IService1.GetAusgabebyIDAsync
            Return MyBase.Channel.GetAusgabebyIDAsync(ID)
        End Function
        
        Public Function GetVerbrauchbyDateAsync(ByVal datum As Date) As System.Threading.Tasks.Task(Of HsVerwSvc.Verbrauch) Implements HsVerwSvc.IService1.GetVerbrauchbyDateAsync
            Return MyBase.Channel.GetVerbrauchbyDateAsync(datum)
        End Function
        
        Public Function GetAusgabebyDateAsync(ByVal datum As Date) As System.Threading.Tasks.Task(Of HsVerwSvc.Ausgabe) Implements HsVerwSvc.IService1.GetAusgabebyDateAsync
            Return MyBase.Channel.GetAusgabebyDateAsync(datum)
        End Function
        
        Public Function GetZahlungsrythmenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Zahlungsrythmus)) Implements HsVerwSvc.IService1.GetZahlungsrythmenAsync
            Return MyBase.Channel.GetZahlungsrythmenAsync
        End Function
        
        Public Function GetEinheitenAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Einheit)) Implements HsVerwSvc.IService1.GetEinheitenAsync
            Return MyBase.Channel.GetEinheitenAsync
        End Function
        
        Public Function GetVarVerbrauchKatAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.VarVerbrauchKat)) Implements HsVerwSvc.IService1.GetVarVerbrauchKatAsync
            Return MyBase.Channel.GetVarVerbrauchKatAsync
        End Function
        
        Public Function SetVerbrauchAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of String) Implements HsVerwSvc.IService1.SetVerbrauchAsync
            Return MyBase.Channel.SetVerbrauchAsync(vlo_verbrauch)
        End Function
        
        Public Function SetAusgabeAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of String) Implements HsVerwSvc.IService1.SetAusgabeAsync
            Return MyBase.Channel.SetAusgabeAsync(vlo_ausgabe)
        End Function
        
        Public Function SetEinnahmeAsync(ByVal vlo_einnahme As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of String) Implements HsVerwSvc.IService1.SetEinnahmeAsync
            Return MyBase.Channel.SetEinnahmeAsync(vlo_einnahme)
        End Function
        
        Public Function SetVerbrauchNewAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of Boolean) Implements HsVerwSvc.IService1.SetVerbrauchNewAsync
            Return MyBase.Channel.SetVerbrauchNewAsync(vlo_verbrauch)
        End Function
        
        Public Function SetAusgabeNewAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of String) Implements HsVerwSvc.IService1.SetAusgabeNewAsync
            Return MyBase.Channel.SetAusgabeNewAsync(vlo_ausgabe)
        End Function
        
        Public Function SetEinnahmeNewAsync(ByVal vlo_ausgabe As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of String) Implements HsVerwSvc.IService1.SetEinnahmeNewAsync
            Return MyBase.Channel.SetEinnahmeNewAsync(vlo_ausgabe)
        End Function
        
        Public Function DeleteVerbrauchAsync(ByVal vlo_verbrauch As HsVerwSvc.Verbrauch) As System.Threading.Tasks.Task(Of Boolean) Implements HsVerwSvc.IService1.DeleteVerbrauchAsync
            Return MyBase.Channel.DeleteVerbrauchAsync(vlo_verbrauch)
        End Function
        
        Public Function DeleteAusgabeAsync(ByVal vlo_ausgabe As HsVerwSvc.Ausgabe) As System.Threading.Tasks.Task(Of Boolean) Implements HsVerwSvc.IService1.DeleteAusgabeAsync
            Return MyBase.Channel.DeleteAusgabeAsync(vlo_ausgabe)
        End Function
        
        Public Function DeleteEinnahmeAsync(ByVal vlo_ausgabe As HsVerwSvc.Einnahme) As System.Threading.Tasks.Task(Of Boolean) Implements HsVerwSvc.IService1.DeleteEinnahmeAsync
            Return MyBase.Channel.DeleteEinnahmeAsync(vlo_ausgabe)
        End Function
        
        Public Function GetHaushaltskategorienAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Haushaltskategorie)) Implements HsVerwSvc.IService1.GetHaushaltskategorienAsync
            Return MyBase.Channel.GetHaushaltskategorienAsync
        End Function
        
        Public Function GetHaushaltsunterkategorienAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of HsVerwSvc.Haushaltsunterkategorie)) Implements HsVerwSvc.IService1.GetHaushaltsunterkategorienAsync
            Return MyBase.Channel.GetHaushaltsunterkategorienAsync
        End Function
        
        Public Function GetAuswertungAsync() As System.Threading.Tasks.Task(Of HsVerwSvc.Auswertung) Implements HsVerwSvc.IService1.GetAuswertungAsync
            Return MyBase.Channel.GetAuswertungAsync
        End Function
        
        Public Function GetEinnahmebyIDAsync(ByVal ID As Long) As System.Threading.Tasks.Task(Of HsVerwSvc.Einnahme) Implements HsVerwSvc.IService1.GetEinnahmebyIDAsync
            Return MyBase.Channel.GetEinnahmebyIDAsync(ID)
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IService1) Then
                Return New System.ServiceModel.EndpointAddress("http://wcfservices.ralfabels.de/HsVerwWCFService/Service1.svc")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1)
        End Function
        
        Public Enum EndpointConfiguration
            
            BasicHttpBinding_IService1
        End Enum
    End Class
End Namespace
